# Generated by Django 4.0.6 on 2022-08-22 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        ('tests', '0001_initial'),
        ('accounts', '0003_delete_corporatemodel'),
        ('corporates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('enroll_number', models.CharField(max_length=20, verbose_name='Enrollement Number')),
                ('age', models.PositiveSmallIntegerField(verbose_name='age')),
                ('student_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_students', to='colleges.collegemodel')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_students', to='colleges.coursemodel')),
                ('skills', models.ManyToManyField(related_name='student_skills', to='corporates.skillmodel')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='StudentTestQuestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleted_option', models.CharField(max_length=1, verbose_name='Selected Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_question', to='tests.questionmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_student', to='students.studentmodel')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_test', to='tests.testmodel')),
            ],
            options={
                'verbose_name': 'Student Test Question',
                'verbose_name_plural': 'Students Tests Questions',
            },
        ),
        migrations.CreateModel(
            name='StudentTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField(default=0, verbose_name='Marks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_studnets', to='students.studentmodel')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tests', to='tests.testmodel')),
            ],
            options={
                'verbose_name': 'Student Test',
                'verbose_name_plural': 'Students Tests',
            },
        ),
    ]
