# Generated by Django 4.0.6 on 2022-08-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='username',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Username'),
        ),
    ]
