# Generated by Django 4.0.6 on 2022-08-17 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_baseuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorporateModel',
        ),
    ]
