# Generated by Django 4.0.6 on 2022-08-22 15:37

import accounts.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_delete_corporatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeModel',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.baseuser',),
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrevation', models.CharField(max_length=10, unique=True, verbose_name='Course Appybbrevation')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
            ],
        ),
        migrations.CreateModel(
            name='CollegesCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NO_DATA', 'No data'), ('UPDATING', 'Updating'), ('UPDATED', 'Updated')], default='NO_DATA', max_length=8, verbose_name='Adding Student Status')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.collegemodel')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='colleges.coursemodel')),
            ],
        ),
    ]
