"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from os import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2_$uxy$j3q*+))$o3s(9#hp_92h*1_)3^p&g2w%t-zvy_73v-c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'channels',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # local
    'accounts',
    'colleges',
    'students',
    'corporates',
    'tests',
    'notify',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates_global')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'addcss': 'accounts.templates.accounts.templatetags.addcss',
            }
        },
    },
]

ASGI_APPLICATION = 'core.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'itgjrfiu',                      
        'USER': 'itgjrfiu',
        'PASSWORD': 'HCh5RpEzIFWVY2gSHo2I3o6g86zQb87R',
        'HOST': 'satao.db.elephantsql.com',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static')
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CRISPY_TEMPLATE_PACK = 'bootstrap3'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.BaseUser'

# Email notification
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST= 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'rohitbst.104764@gmail.com'
EMAIL_HOST_PASSWORD = 'lxsfheiqpnpmcjsl'
EMAIL_USE_TLS= True
DEFAULT_FROM_EMAIL = 'Employeed <rohitbst.104764@gmail.com>'

LOGOUT_REDIRECT_URL = 'home'
LOGIN_REDIRECT_URL = 'home'


# Logging SetUp
LOGGING = {
    'version': 1,                       # the dictConfig format version
    'disable_existing_loggers': False,  # retain the default loggers
    
    'formatters' : {
        'verbose': {
            'format': '>> LOG : {name} {levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '>> LOG : {levelname} "{message}"',
            'style': '{',
        },
    },
    
    'handlers': {
        'console' : {
            'class' : 'logging.StreamHandler',
            'level' : 'DEBUG',
            'formatter' : 'simple',
        }
    },

    'loggers' : {
        'accounts.views' : {
            'level' : 'DEBUG',
            'handlers': ['console'],
        },
        'accounts.utils' : {
            'level' : 'DEBUG',
            'handlers': ['console'],
        },
        'colleges.views' : {
            'level' : 'DEBUG',
            'handlers': ['console'],
        },
        'colleges.tasks' : {
            'level' : 'DEBUG',
            'handlers': ['console'],
        },
        'colleges.utils' : {
            'level' : 'DEBUG',
            'handlers': ['console'],
        }, 
        'corporates.views' : {
            'level' : 'DEBUG',
            'handlers': ['console'],
        },
        'corporates.tasks' : {
            'level' : 'DEBUG',
            'handlers': ['console'],
        },
        'corporates.utils' : {
            'level' : 'DEBUG',
            'handlers': ['console'],
        }, 
        'students.views' : {
            'level' : 'DEBUG',
            'handlers': ['console'],
        },
    }
}


# channel layer setting
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

CELERY_BROKER_URL = 'amqps://uulzkxeo:7eNE01AL1y4flIgPHp2Ohpr4PUFlBNJs@puffin.rmq2.cloudamqp.com/uulzkxeo'

DOMAIN = 'http://127.0.0.1:8000'